Vagrant.configure("2") do |config|

  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/bionic64"
    dev.vm.network "private_network", ip: "192.168.200.30"
    dev.vm.synced_folder "../", "/vagrant",mount_options: ["dmode=777,fmode=777"]

    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.name = "peppol-bis-invoice"
    end

    dev.vm.provision "ansible_local" do |ansible|
      ansible.playbook = 'Vagrant/playbook.yml'
      ansible.extra_vars = {
          public_url: "192.168.200.30"
      }

    end
  end
end