- name: Add Certbot (let's encrypt) executable
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    filename: 'certbot'

- name: Add apt modules
  apt:
    name: ["certbot", "python-certbot-apache"]
    state: present

- name: Stop nginx to allow intallation of certificate using certbot
  service:
    name: "nginx"
    state: stopped

- debug:
    msg: SSL Config {{ configure_ssl }}

- include: ssl.yml
  when: configure_ssl == True

- name: Copy default site config for nginx in sites-available
  template:
    src: "templates/000-default.site.j2"
    dest: "/etc/nginx/sites-available/000-default.conf"
    mode: 0644
  when: configure_ssl == False

- name: Copy default site config (with SSL Redirect) in sites-available
  template:
    src: "templates/000-default.site.with.redirect.j2"
    dest: "/etc/nginx/sites-available/000-default.conf"
    mode: 0644
  when: configure_ssl == True


- name: enable default site (http)
  file:
    src: "/etc/nginx/sites-available/000-default.conf"
    dest: "/etc/nginx/sites-enabled/000-default.conf"
    state: link


- name: Restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
