- name: Check if an SSL certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{public_url}}/cert.pem"
  register: letsencrypt_cert

- name: Run certbot to generate certificates if not present
  shell: certbot certonly --standalone --noninteractive --agree-tos --email jerdimitriou@gmail.com -d www.avoravo.com
  when: letsencrypt_cert.stat.exists == False

- name: periodically check and renew certificates (every week)
  cron:
    name: "Check and renew certificates weekly"
    special_time: weekly
    job: 'certbot renew --pre-hook "service apache2 stop" --post-hook "service apache2 start"'

- name: Copy default site config for apache (SSL)
  template:
    src: "templates/000-default.site.ssl.j2"
    dest: "/etc/apache2/sites-available/000-default-le-ssl.conf"
    mode: 0644

- name: enable default site (SSL)
  file:
    src: "/etc/apache2/sites-available/000-default-le-ssl.conf"
    dest: "/etc/apache2/sites-enabled/000-default-le-ssl.conf"
    state: link

- name: copy SSL Options
  copy:
    src: options-ssl-apache.conf
    dest: "/etc/letsencrypt/options-ssl-apache.conf"
